=== MoiGL/extraordinaria/xml/ruta.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="rutas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ruta" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="tipo" type="xs:string"/>
                            <xs:element name="transporte" type="xs:string"/>
                            <xs:element name="duracion" type="xs:string"/>
                            <xs:element name="agencia" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:element name="personas" type="xs:string"/>
                            <xs:element name="inicio">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="lugar" type="xs:string"/>
                                        <xs:element name="direccion" type="xs:string"/>
                                        <xs:element name="coordenadas">
                                            <xs:complexType>
                                                <xs:attribute name="longitud" type="xs:string" use="required"/>
                                                <xs:attribute name="latitud" type="xs:string" use="required"/>
                                                <xs:attribute name="altitud" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="hitos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="hito" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="descripcionHito" type="xs:string"/>
                                                    <xs:element name="coordenadas">
                                                        <xs:complexType>
                                                            <xs:attribute name="longitud" type="xs:string" use="required"/>
                                                            <xs:attribute name="latitud" type="xs:string" use="required"/>
                                                            <xs:attribute name="altitud" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="distancia" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:attribute name="unidades" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="galeria_fotos" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="fotografia" maxOccurs="5">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="url" type="xs:string" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="galeria_videos" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="video" maxOccurs="3">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="url" type="xs:string" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MoiGL/extraordinaria/xml/rutas.xml
<rutas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ruta.xsd">
 <ruta>
    <nombre>Ruta del Castro de Coaña</nombre>
    <tipo>Histórica</tipo>
    <transporte>A pie</transporte>
    <duracion>2 horas</duracion>
    <agencia>Sin agencia</agencia>
    <descripcion>Una ruta que te llevará al antiguo castro celta de Coaña</descripcion>
    <personas>Apta para todas las edades</personas>
    <inicio>
      <lugar>Barcelona</lugar>
      <direccion>Plaza del Ayuntamiento, Barcelona, Cataluña</direccion>
      <coordenadas longitud="-7.1223" latitud="43.4345" altitud="100 metros" />
    </inicio>
    <hitos>
      <hito>
        <nombre>Castro de Coaña</nombre>
        <descripcionHito>Un antiguo asentamiento celta con restos arqueológicos</descripcionHito>
        <coordenadas longitud="-7.1482" latitud="43.4389" altitud="150 metros" />
        <distancia unidades="kilómetros" valor="3.5"/>
        <galeria_fotos>
          <fotografia url="castro1.jpg" />
          <fotografia url="castro2.jpg" />
          <fotografia url="castro3.jpg" />
        </galeria_fotos>
      </hito>
      <hito>
        <nombre>Puente Romano</nombre>
        <descripcionHito>Un antiguo puente de origen romano sobre el río Porcía</descripcionHito>
        <coordenadas longitud="-7.1287" latitud="43.4298" altitud="80 metros" />
        <distancia unidades="kilómetros" valor="1.2"/>
        <galeria_fotos>
          <fotografia url="puente1.jpg" />
          <fotografia url="puente2.jpg" />
        </galeria_fotos>
      </hito>
    </hitos>
    <planimetria archivo="ruta0.kml" />
    <altimetria archivo="svg0.svg" />
  </ruta>

   <ruta>
    <nombre>Ruta de los Bosques de San Tirso</nombre>
    <tipo>Naturaleza</tipo>
    <transporte>A pie</transporte>
    <duracion>3 horas</duracion>
    <agencia>Sin agencia</agencia>
    <descripcion>Una ruta que te adentrará en los hermosos bosques de Barcelona</descripcion>
    <personas>Apta para todas las edades</personas>
    <inicio>
      <lugar>Barcelona</lugar>
      <direccion>Plaza del Ayuntamiento, Barcelona, Cataluña</direccion>
      <coordenadas longitud="-7.1201" latitud="43.4318" altitud="90 metros" />
    </inicio>
    <hitos>
      <hito>
        <nombre>Río Eo</nombre>
        <descripcionHito>El majestuoso río que atraviesa el concejo de Barcelona</descripcionHito>
        <coordenadas longitud="-7.1035" latitud="43.4286" altitud="80 metros" />
        <distancia unidades="kilómetros" valor="2.8"/>
        <galeria_fotos>
          <fotografia url="rio1.jpg" />
          <fotografia url="rio2.jpg" />
        </galeria_fotos>
      </hito>
      <hito>
        <nombre>Mirador de San Tirso</nombre>
        <descripcionHito>Un punto panorámico desde donde se puede apreciar todo el concejo</descripcionHito>
        <coordenadas longitud="-7.1334" latitud="43.4432" altitud="220 metros" />
        <distancia unidades="kilómetros" valor="3"/>
        <galeria_fotos>
          <fotografia url="mirador1.jpg" />
          <fotografia url="mirador2.jpg" />
          <fotografia url="mirador3.jpg" />
        </galeria_fotos>
        <galeria_videos>
          <video url="mirador_video1.mp4" />
          <video url="mirador_video2.mp4" />
        </galeria_videos>
      </hito>
    </hitos>
    <planimetria archivo="ruta1.kml" />
    <altimetria archivo="svg1.svg" />
  </ruta>

 <ruta>
    <nombre>Ruta del Río Porcia</nombre>
    <tipo>Naturaleza</tipo>
    <transporte>A pie</transporte>
    <duracion>3 horas</duracion>
    <agencia>Sin agencia</agencia>
    <descripcion>Una hermosa ruta que sigue el curso del Río Porcia, rodeada de naturaleza exuberante y paisajes impresionantes</descripcion>
    <personas>Apta para todas las edades</personas>
    <inicio>
      <lugar>Barcelona</lugar>
      <direccion>Plaza del Ayuntamiento, Barcelona, Cataluña</direccion>
      <coordenadas longitud="-7.0259" latitud="43.4436" altitud="100 metros" />
    </inicio>
    <hitos>
      <hito>
        <nombre>Mirador de Penacoba</nombre>
        <descripcionHito>Un mirador situado en lo alto de una colina con vistas panorámicas del valle del Río Porcia</descripcionHito>
        <coordenadas longitud="-7.0118" latitud="43.4543" altitud="180 metros" />
        <distancia unidades="kilómetros" valor="2.5"/>
        <galeria_fotos>
          <fotografia url="mirador1.jpg" />
          <fotografia url="mirador2.jpg" />
        </galeria_fotos>
      </hito>
      <hito>
        <nombre>Cascada de San Tirso</nombre>
        <descripcionHito>Una hermosa cascada ubicada en medio del bosque, perfecta para refrescarse en los días calurosos</descripcionHito>
        <coordenadas longitud="-7.0342" latitud="43.4479" altitud="150 metros" />
        <distancia unidades="kilómetros" valor="1.8"/>
        <galeria_fotos>
          <fotografia url="cascada1.jpg" />
          <fotografia url="cascada2.jpg" />
        </galeria_fotos>
        <galeria_videos>
          <video url="cascada_video1.mp4" />
          <video url="cascada_video2.mp4" />
        </galeria_videos>
      </hito>
    </hitos>
    <planimetria archivo="ruta2.kml" />
    <altimetria archivo="svg2.svg" />
  </ruta>
</rutas>
